server:
  port: ${port:8090}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://127.0.0.1:8761/eureka/}

spring:
  application:
    name: Hi
  zipkin:
    base-url: http://localhost:9200
